### ISSUE TITLE
Is serializing to .dep / .tas really needed?

### ISSUE THREAD

**Issue by dharhas** [ContinuumIO/whitebox-geospatial-analysis-tools#6]
So I did a bit of research. Looks like the .dep/.tas combination is a in-house format that Whitebox uses (Also called Whitebox GAT).

http://www.unc.edu/courses/2010spring/geog/591/001/software/bin/Help/FileFormatsDescriptions.html
 
Whitebox supports lots of standard formats:

> The WhiteboxTools library can currently support read/writing raster data in Whitebox GAT, GeoTIFF, ESRI (ArcGIS) ASCII and binary (.flt & .hdr), GRASS GIS, Idrisi, SAGA GIS (binary and ASCII), and Surfer 7 data formats.

To me it makes more sense to serialize to a standard format like geotiff than serializing to a format only Whitebox can read.

Is there another reason to serialize to .dep/.tas files?

**Comment by jbednar** [comment]
Well, the serial format is meant to be an implementation detail in this case, not something for users to mess with, and if it's an in-house format, it may be able to preserve some metadata that's not expressible in the interchangeable formats.  Still, the standard formats might be useful for debugging, and could e.g. have some higher investment in optimized loading or saving, so they could offer some advantages even if it's just behind the scenes.

**Comment by dharhas** [comment]
If it is an implementation detail and things are set automatically, then I don't particularly care. I was under the impression after our discussion that we had to specify metadata manually before we could use the tools which would be a pain. Feel free to close.

**Comment by PeterDSteinberg** [comment]
One change in PR #8 was to try to serialize the `xarray.DataArray`'s `attrs` and then call `add_dep_meta` if the required metadata are not found.  See [this part of the PR's changed files](https://github.com/ContinuumIO/whitebox-geospatial-analysis-tools/pull/8/files#diff-4c2fb17900477eb3f6a0d2d0a867a37aR274) .  I'll close this issue for now - I do think the .dep / .tas IO is an implementation detail.  We can discuss further in September how / when to provide support for all the file types WhiteBox supports, e.g. lidar .las/.laz data.  Here's an example of using GeoTiff from USGS NED:

```
from whitebox_tools import *
filled = FillDepressions(dem='/Users/psteinberg/Downloads/ASTGTM2_N00E006/ASTGTM2_N00E006_dem.tif')
Running: /Users/psteinberg/Documents/earth/whitebox-geospatial-analysis-tools/whitebox_tools/target/release/whitebox_tools '--run="FillDepressions"' '--output="/Users/psteinberg/.whitebox_tools_tempdir/output-THMyFEr.dep"' '--dem="/Users/psteinberg/Downloads/ASTGTM2_N00E006/ASTGTM2_N00E006_dem.tif"' '--wd="/Users/psteinberg/Documents/earth/EarthSim"' -v
******************************
* Welcome to FillDepressions *
******************************
Reading data...
progress: 0%
Progress: 100%
Saving data...
Output file written
Elapsed time: 2.874311s
```
