### ISSUE TITLE
Unable to run the tools: Illegal instruction: 4

### ISSUE THREAD

**Issue by dharhas** [ContinuumIO/whitebox-geospatial-analysis-tools#9]
help works:

`/Users/rditldp9/miniconda3/envs/earthsim/share/whitebox_tools/release/whitebox_tools --help`

most other things fail:

```
/Users/rditldp9/miniconda3/envs/earthsim/share/whitebox_tools/release/whitebox_tools --listtools
Illegal instruction: 4
```

First noticed when calling from python and then tried cli since python error was not informative.

I'm on OS X Sierra (`uname -a
Darwin ITLDP9-MD-Q3134 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`)

**Comment by dharhas** [comment]
@PeterDSteinberg 

I was able to make a conda build on my Mac that seems to be working.

I have to modify setup.py to include:

setup(...
          ...
          extra_link_args = ["-headerpad_max_install_names",]
)

to avoid and install_name_tool error on OS X

you can install from:

conda install -c dharhas/label/earthsim whitebox_tools

Not sure what the whole 'label' business is, anaconda.org must have changed something, I couldn't work out how not to have a label.

**Comment by gbrener** [comment]
Thank you @dharhas - just merged in this fix. The updated packages should now be available on Peter's anaconda.org channel (`psteinberg`).
